### ISSUE TITLE
System.OutOfMemoryException starting yesterday

### ISSUE THREAD

**Issue by savornicesei** [NAnt2/NAnt2#54]
<a href="https://github.com/jholovacs"><img src="https://avatars0.githubusercontent.com/u/1767540?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jholovacs](https://github.com/jholovacs)**
_Tuesday Dec 22, 2015 at 21:26 GMT_
_Originally opened as https://github.com/nant/nant/issues/162_

----

We're suddenly seeing this in our build logs (bamboo) starting yesterday:

22-Dec-2015 14:40:38    INTERNAL ERROR
22-Dec-2015 14:40:38  
22-Dec-2015 14:40:38    System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
22-Dec-2015 14:40:38       at System.String.ReplaceInternal(String oldValue, String newValue)
22-Dec-2015 14:40:38       at System.String.Replace(String oldValue, String newValue)
22-Dec-2015 14:40:38       at NAnt.Core.DefaultLogger.OutputMessage(BuildEventArgs e, Int32 indentationLength)
22-Dec-2015 14:40:38       at NAnt.Core.Tasks.EchoTask.ExecuteTask()
22-Dec-2015 14:40:38       at NAnt.Core.Task.Execute()
22-Dec-2015 14:40:38       at NAnt.Core.Target.Execute()
22-Dec-2015 14:40:38       at NAnt.Core.Project.Execute(String targetName, Boolean forceDependencies)
22-Dec-2015 14:40:38       at NAnt.Core.Task.Execute()
22-Dec-2015 14:40:38       at NAnt.Core.Target.Execute()
22-Dec-2015 14:40:38       at NAnt.Core.Project.Execute(String targetName, Boolean forceDependencies)
22-Dec-2015 14:40:38       at NAnt.Core.Project.Execute()
22-Dec-2015 14:40:38       at NAnt.Core.Project.Run()
22-Dec-2015 14:40:38  
22-Dec-2015 14:40:38    Please send bug report to nant-developers@lists.sourceforge.net.

This error occurs against .91 and .92.  Any ideas?

**Comment by savornicesei** [comment]
<a href="https://github.com/ChrisJacquesPayfactors"><img src="https://avatars1.githubusercontent.com/u/22477306?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ChrisJacquesPayfactors](https://github.com/ChrisJacquesPayfactors)**
_Monday Apr 03, 2017 at 15:18 GMT_

----

Ditto

**Comment by savornicesei** [comment]
Old ticket with insufficient details.
